[project]
name = "cfjson"
version = "0.4.1"
description = "CF-JSON converters"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Alex Port", email = "alex.port@metocean.com" },
    { name = "Simon Erkelens", email = "simon.erkelens@metservice.com" }
]
license = "Apache-2.0"
dependencies = [
    "numpy>=2.4.0",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "python-dateutil>=2.7.0",
    "six>=1.17.0",
    "xarray>=2026.7.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.6.2",
    "mock>=5.2.0",
    "netcdf4>=1.7.4",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[build-system]
requires = [
    "uv_build >= 0.12.10, <0.13.0"
]
build-backend = "uv_build"