name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        # Install a specific version of uv.
        version: "0.12.3"
    - name: install Python
      run: uv python install
    - name: Run tests
      run: |
        uv run pytest --cov=cfjson --cov-report term-missing

